author: ['DoctorReid']
planet: '空间站黑塔'
region: '收容舱段'
floor: 1
tp: '毁灭之蕾拟造花萼赤'
route:
  - op: 'move'
    data: [318, 445, -1]
  - op: 'move'
    data: [257, 440]
  - op: 'move'
    data: [257, 325]
  - op: 'move'
    data: [222, 325]
  - op: 'move'
    data: [207, 415]
  - op: 'patrol'
