mini_map:
  r: 93
  x: 141
  y: 151
walk_speed: 20
run_speed: 25
turn_dx: 0
server_region: CN
run_mode: 0
key_interact: 'f'
key_technique: 'e'
key_open_map: 'm'
key_esc: 'esc'
lang: 'cn'
game_path: ''
proxy_type: 'none'
personal_proxy: ''