author: ['DoctorReid']
planet: '雅利洛'
region: '城郊雪原'
floor: 0
tp: '回忆之蕾拟造花萼金'
route:
  - op: 'move'
    data: [1067, 477]
  - op: 'move'
    data: [1013, 583]
  - op: 'move'
    data: [933, 485]
  - op: 'patrol'
  - op: 'move'
    data: [1025, 287]
  - op: 'move'
    data: [843, 281]
  - op: 'move'
    data: [711, 316]
  - op: 'patrol'
  - op: 'move'
    data: [674, 236]
  - op: 'patrol'
