author: ['DoctorReid']
planet: '雅利洛'
region: '边缘通路'
floor: 0
tp: '歌德旧宅'
route:
  - op: 'move'
    data: [750, 261]
  - op: 'move'
    data: [683, 326]
  - op: 'patrol'
  - op: 'move'
    data: [690, 354]
  - op: 'patrol'
  - op: 'move'
    data: [693, 510]
  - op: 'move'
    data: [665, 516]
  - op: 'move'
    data: [660, 610]
  - op: 'patrol'
  - op: 'move'
    data: [662, 635]
  - op: 'move'
    data: [746, 640]
  - op: 'move'
    data: [746, 680]
  - op: 'patrol'
  - op: 'move'
    data: [747, 717]
  - op: 'patrol'
  - op: 'move'
    data: [746, 788]
  - op: 'patrol'
  - op: 'move'
    data: [686, 851]
  - op: 'move'
    data: [686, 955]
  - op: 'patrol'
