author: ['DoctorReid', '龙女姬']
planet: '雅利洛'
region: '残响回廊'
floor: 0
tp: '古战场前线'
route:
  - op: 'move'
    data: [490, 1232]
  - op: 'move'
    data: [488, 1155]
  - op: 'patrol'
  - op: 'move'
    data: [488, 1176]
  - op: 'move'
    data: [414, 1175]
  - op: 'patrol'
  - op: 'move'
    data: [319, 1190]
  - op: 'move'
    data: [265, 1190]
  - op: 'move'
    data: [265, 1320]
  - op: 'patrol'
  - op: 'move'
    data: [303, 1320]
  - op: 'patrol'
