author: ['DoctorReid', '龙女姬']
planet: '雅利洛'
region: '残响回廊'
floor: 0
tp: '鸣雷之形凝滞虚影'
route:
  - op: 'move'
    data: [520, 610]
  - op: 'move'
    data: [555, 610]
  - op: 'move'
    data: [556, 540]
  - op: 'move'
    data: [658, 546]
  - op: 'move'
    data: [678, 567]
  - op: 'patrol'
  - op: 'move'
    data: [740, 627]
  - op: 'move'
    data: [718, 647]
  - op: 'move'
    data: [697, 663]
  - op: 'patrol'
  - op: 'move'
    data: [668, 663]
  - op: 'move'
    data: [650, 648]
  - op: 'patrol'
