author: ['DoctorReid']
planet: '雅利洛'
region: '永冬岭'
floor: 0
tp: '睿治之径'
route:
  - op: 'move'
    data: [560, 553]
  - op: 'move'
    data: [604, 534]
  - op: 'move'
    data: [627, 545]
  - op: 'move'
    data: [653, 557]
  - op: 'patrol'
