author: ['DoctorReid']
planet: '雅利洛'
region: '大矿区'
floor: 0
tp: '俯瞰点'
route:
  - op: 'move'
    data: [616, 657]
  - op: 'move'
    data: [679, 642]
  - op: 'patrol'
  - op: 'move'
    data: [694, 574]
  - op: 'patrol'
  - op: 'move'
    data: [770, 565]
  - op: 'move'
    data: [768, 638]
  - op: 'move'
    data: [732, 688]
  - op: 'move'
    data: [706, 705]
  - op: 'move'
    data: [687, 709]
  - op: 'patrol'
  - op: 'move'
    data: [642, 742]
  - op: 'patrol'
  - op: 'move'
    data: [596, 735]
  - op: 'move'
    data: [555, 720]
  - op: 'move'
    data: [492, 733]
  - op: 'move'
    data: [397, 682]
  - op: 'patrol'
  - op: 'move'
    data: [376, 622]
  - op: 'patrol'
  - op: 'move'
    data: [413, 611]
  - op: 'move'
    data: [467, 665]
  - op: 'move'
    data: [497, 662]
  - op: 'move'
    data: [521, 628]
  - op: 'patrol'
