author: ['DoctorReid', '龙女姬']
planet: '雅利洛'
region: '铆钉镇'
floor: 1
tp: '巽风之形凝滞虚影'
route:
  - op: 'move'
    data: [603, 459]
  - op: 'move'
    data: [673, 459]
  - op: 'move'
    data: [702, 412]
  - op: 'move'
    data: [732, 417]
  - op: 'patrol'
  - op: 'move'
    data: [732, 479]
  - op: 'patrol'
  - op: 'move'
    data: [733, 515]
  - op: 'patrol'
