author: ['DoctorReid']
planet: '雅利洛'
region: '机械聚落'
floor: 1
tp: '同谐之蕾拟造花萼赤'
route:
  - op: 'move'
    data: [312, 531]
  - op: 'patrol'
  - op: 'move'
    data: [347, 548]
  - op: 'move'
    data: [402, 533]
  - op: 'move'
    data: [410, 485]
  - op: 'move'
    data: [410, 420]
  - op: 'patrol'
  - op: 'move'
    data: [415, 482]
  - op: 'move'
    data: [433, 482]
  - op: 'move'
    data: [612, 487]
  - op: 'move'
    data: [635, 486]
  - op: 'move'
    data: [676, 493]
  - op: 'move'
    data: [724, 451]
  - op: 'patrol'
  - op: 'move'
    data: [715, 423]
  - op: 'patrol'
  - op: 'move'
    data: [737, 477]
  - op: 'move'
    data: [771, 500]
  - op: 'patrol'
