author: ['DoctorReid']
planet: '仙舟罗浮'
region: '流云渡'
floor: 1
tp: '积玉坊'
route:
  - op: 'move'
    data: [566, 754]
  - op: 'move'
    data: [595, 752]
  - op: 'move'
    data: [719, 726]
  - op: 'move'
    data: [819, 726]
  - op: 'move'
    data: [855, 670]
  - op: 'patrol'
  - op: 'move'
    data: [885, 670]
  - op: 'patrol'
