author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '流云渡'
floor: 1
tp: '积玉坊'
route:
  - op: 'move'
    data: [566, 754]
  - op: 'move'
    data: [585, 750]
  - op: 'move'
    data: [596, 735]
  - op: 'move'
    data: [597, 700]
  - op: 'move'
    data: [597, 679, 2]
  - op: 'move'
    data: [597, 661]
  - op: 'move'
    data: [555, 660]
  - op: 'patrol'
  - op: 'move'
    data: [520, 660]
  - op: 'patrol'
