author: ['DoctorReid']
planet: '仙舟罗浮'
region: '廻星港'
floor: 1
tp: '植船区萌甲'
route:
  - op: 'move'
    data: [442, 488]
  - op: 'move'
    data: [423, 486]
  - op: 'move'
    data: [422, 445]
  - op: 'move'
    data: [322, 442]
  - op: 'move'
    data: [318, 560]
  - op: 'move'
    data: [369, 560]
  - op: 'patrol'
  - op: 'move'
    data: [380, 560]
  - op: 'move'
    data: [380, 527]
  - op: 'move'
    data: [424, 526]
  - op: 'move'
    data: [426, 584]
  - op: 'move'
    data: [427, 617]
  - op: 'move'
    data: [415, 620]
  - op: 'move'
    data: [409, 680]
  - op: 'patrol'
  - op: 'move'
    data: [402, 720]
  - op: 'patrol'
  - op: 'move'
    data: [394, 756]
  - op: 'move'
    data: [309, 753]
  - op: 'slow_move'
    data: [312, 784]
  - op: 'slow_move'
    data: [325, 784]
  - op: 'patrol'
  - op: 'slow_move'
    data: [312, 784]
  - op: 'slow_move'
    data: [309, 753]
  - op: 'move'
    data: [394, 756]
  - op: 'move'
    data: [388, 803]
  - op: 'move'
    data: [426, 814]
  - op: 'move'
    data: [483, 815]
  - op: 'move'
    data: [512, 808]
  - op: 'move'
    data: [565, 811]
  - op: 'move'
    data: [579, 780]
  - op: 'patrol'
