author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '太卜司'
floor: 1
tp: '界寰阵'
route:
  - op: 'move'
    data: [383, 240]
  - op: 'move'
    data: [387, 220]
  - op: 'wait'
    data: ['seconds', '1']
  - op: 'move'
    data: [431, 173]
  - op: 'move'
    data: [490, 171]
  - op: 'move'
    data: [520, 156]
  - op: 'wait'
    data: ['seconds', '1']
  - op: 'move'
    data: [540, 169]
  - op: 'wait'
    data: ['seconds', '1']
  - op: 'slow_move'
    data: [587, 170]
  - op: 'interact'
    data: '入画'
  - op: 'wait'
    data: ['seconds', '3']
  - op: 'wait'
    data: ['in_world', '20']
  - op: 'update_pos'
    data: [690, 224]
  - op: 'move'
    data: [706, 237]
  - op: 'move'
    data: [736, 271]
  - op: 'patrol'
  - op: 'move'
    data: [781, 314]
  - op: 'wait'
    data: ['seconds', '1']
  - op: 'move'
    data: [782, 379]
  - op: 'move'
    data: [759, 415]
  - op: 'wait'
    data: ['seconds', '1']
  - op: 'move'
    data: [835, 415]
  - op: 'move'
    data: [871, 394]
  - op: 'move'
    data: [907, 395]
  - op: 'move'
    data: [930, 368]
  - op: 'patrol'
  - op: 'move'
    data: [931, 416]
  - op: 'move'
    data: [1010, 416]
  - op: 'move'
    data: [1010, 450]
  - op: 'patrol'
  - op: 'move'
    data: [1029, 361]
  - op: 'patrol'
