author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '太卜司'
floor: 2
tp: '祥台'
route:
  - op: 'move'
    data: [469, 1168]
  - op: 'move'
    data: [506, 1166]
  - op: 'move'
    data: [533, 1107]
  - op: 'patrol'
  - op: 'move'
    data: [535, 1034]
  - op: 'move'
    data: [610, 1031]
  - op: 'move'
    data: [638, 1030]
  - op: 'move'
    data: [673, 1030]
  - op: 'patrol'
  - op: 'move'
    data: [638, 1030]
  - op: 'move'
    data: [610, 1031]
  - op: 'move'
    data: [537, 1006]
  - op: 'move'
    data: [534, 906]
  - op: 'move'
    data: [561, 902]
  - op: 'patrol'
  - op: 'move'
    data: [561, 851]
  - op: 'patrol'
  - op: 'move'
    data: [503, 850]
  - op: 'move'
    data: [503, 880]
  - op: 'move'
    data: [465, 881]
  - op: 'move'
    data: [299, 875]
  - op: 'patrol'
