author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '工造司'
floor: 0
tp: '镕金坊通道'
route:
  - op: 'move'
    data: [793, 601]
  - op: 'move'
    data: [796, 502]
  - op: 'move'
    data: [911, 502]
  - op: 'patrol'
  - op: 'move'
    data: [943, 502]
  - op: 'patrol'
  - op: 'move'
    data: [796, 502]
  - op: 'move'
    data: [798, 431]
  - op: 'move'
    data: [779, 431]
  - op: 'move'
    data: [779, 444]
  - op: 'patrol'
  - op: 'move'
    data: [779, 405]
  - op: 'move'
    data: [864, 405]
  - op: 'move'
    data: [855, 312]
  - op: 'move'
    data: [884, 311]
  - op: 'patrol'
  - op: 'move'
    data: [880, 258]
  - op: 'move'
    data: [810, 258]
  - op: 'slow_move'
    data: [775, 258]
  - op: 'interact'
    data: '入画'
  - op: 'wait'
    data: ['seconds', '3']
  - op: 'wait'
    data: ['in_world', '20']
  - op: 'update_pos'
    data: [558, 321]
  - op: 'move'
    data: [444, 333]
  - op: 'patrol'
  - op: 'move'
    data: [407, 346]
  - op: 'patrol'
  - op: 'move'
    data: [370, 410]
  - op: 'move'
    data: [368, 321]
  - op: 'move'
    data: [344, 334]
  - op: 'patrol'
  - op: 'move'
    data: [343, 414]
  - op: 'patrol'
