author: ['DoctorReid', '1224910892']
planet: '仙舟罗浮'
region: '丹鼎司'
level: 1
tp: '太真丹室'
route:
  - op: 'move'
    data: [550, 567]
  - op: 'move'
    data: [521, 594]
  - op: 'move'
    data: [465, 596]
  - op: 'move'
    data: [455, 606]
  - op: 'move'
    data: [441, 597]
  - op: 'move'
    data: [390, 596]
  - op: 'move'
    data: [346, 557]
  - op: 'patrol'
  - op: 'move'
    data: [323, 559]
  - op: 'move'
    data: [317, 527]
  - op: 'move'
    data: [292, 500]
  - op: 'move'
    data: [292, 444]
  - op: 'move'
    data: [267, 444]
  - op: 'move'
    data: [269, 413]
  - op: 'move'
    data: [305, 411]
  - op: 'move'
    data: [311, 430]
  - op: 'patrol'
  - op: 'move'
    data: [380, 430]
  - op: 'move'
    data: [434, 496]
  - op: 'move'
    data: [485, 491]
  - op: 'move'
    data: [523, 454]
  - op: 'move'
    data: [515, 386]
  - op: 'patrol'
