author: ['DoctorReid', '龙女姬']
planet: '仙舟罗浮'
region: '丹鼎司'
floor: 2
tp: '药使之径侵蚀隧洞'
route:
  - op: 'move'
    data: [669, 1458]
  - op: 'move'
    data: [684, 1389]
  - op: 'patrol'
  - op: 'move'
    data: [712, 1358]
  - op: 'move'
    data: [759, 1315]
  - op: 'patrol'
  - op: 'move'
    data: [712, 1358]
  - op: 'move'
    data: [684, 1389]
  - op: 'move'
    data: [669, 1458]
  - op: 'move'
    data: [650, 1478]
  - op: 'move'
    data: [579, 1478]
  - op: 'move'
    data: [577, 1374]
  - op: 'move'
    data: [644, 1317]
  - op: 'move'
    data: [725, 1224]
  - op: 'move'
    data: [742, 1132]
  - op: 'patrol'
  - op: 'move'
    data: [781, 1155]
  - op: 'patrol'
  - op: 'move'
    data: [782, 1106]
  - op: 'patrol'
  - op: 'move'
    data: [741, 1103]
  - op: 'patrol'
  - op: 'move'
    data: [754, 1053]
  - op: 'move'
    data: [708, 1016]
  - op: 'move'
    data: [556, 1017]
  - op: 'patrol'
  - op: 'move'
    data: [559, 975]
  - op: 'patrol'
